### ISSUE TITLE
Scan resulting in no device found

### ISSUE THREAD

**Issue by SahajRana** [RobotPajamas/Blueteeth#26] opened 2017-08-15 08:22 UTC
This is the code:

``BlueteethManager.with(this).scanForPeripherals(DEVICE_SCAN_MILLISECONDS, bleDevices -> {
            Timber.d("On Scan completed");
            Log.e("SahajLOG", "scan complete" +bleDevices);
            mProgressBar.setVisibility(View.GONE);
            for (BlueteethDevice device : bleDevices) {
                Log.e("SahajLOG", "device.getBluetoothDevice().getName(): " +device.getBluetoothDevice().getName());
                if (!TextUtils.isEmpty(device.getBluetoothDevice().getName())) {
                    Timber.d("%s - %s", device.getName(), device.getMacAddress());
                    mRecyclerView.post(new Runnable() {
                        @Override
                        public void run() {
                            Device_recycleradapter_item mDevice= new Device_recycleradapter_item();
                            mDevice.setContext(MainActivity.this);
                            mDevice.setmDeviceName(device.getName());
                            mDevice.setmMacAddress(device.getMacAddress());
                            mFastItemAdapter.add(mDevice);
                        }
                    });
                }
            }
        });``

in logcat:

> sahaj.bluice E/SahajLOG: scan complete[]

the devices returned is empty.

**Comment by sureshjoshi** [comment] 2017-12-12 16:32
Which API level is this? Which OS/phone? Did you check for runtime permissions?

**Comment by sureshjoshi** [comment] 2017-12-13 06:35
Closing as possible dupe of #27 - please re-open if that's not the case

**Closed as completed by sureshjoshi** 2017-12-13 06:35 UTC
